<a href="https://colab.research.google.com/github/rohailkhan/Aj_Machine_learning_master/blob/main/Task_2_Build_a_predictive_model_using_a_train_test_split_Use_the_December_fail_logs_as_the_test_data_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

address='/content/drive/MyDrive/Afujitsu/Task Data_ Server Down Data.xlsx'
df = pd.read_excel (r'/content/drive/MyDrive/Afujitsu/Task Data_ Server Down Data.xlsx', sheet_name='Fail Logs')
df1=df[0:40].drop(columns='Asset ID')
df1['Fail Month'] = df1['Fail Month'].replace(['July','August','September','October','November','December'],[7,8,9,10,11,12])


# making classes in downtime
groups = ['Low', 'Med', 'High', 'Very High']
df1['Downtime (GROUPS)']=pd.qcut(df1['Downtime (Min)'], q=4,labels=groups)

# convert date time to numeric
from datetime import datetime
a = datetime.now()
d=[]
# Converting a to string in the desired format (YYYYMMDD) using strftime
# and then to int.
a = datetime.now()

for date in df7['Fail Date']:
  d.append(int(a.strftime('%Y%m%d')))
df7['date_numeric']=d

# X and Y for selecting base model
X=df7.drop(columns=['Downtime (Min)','Downtime (GROUPS)','Fail Date','date_numeric'])
Y=df7['Downtime (GROUPS)']

# selecting decemeber as test
train=df7.iloc[0:32,:]
test=df7.iloc[32:40,:]



# Standaderdize the X and Y data

standard=StandardScaler()

standard_X_train_fit=standard.fit(X)
X_T=standard_X_train_fit.transform(X)


# split Train and test data

X_train=train.drop(columns=['Downtime (GROUPS)','Fail Date','Downtime (Min)','date_numeric']).values
Y_train=train['Downtime (GROUPS)']

X_test=test.drop(columns=['Downtime (GROUPS)','Fail Date','Downtime (Min)','date_numeric']).values
Y_test=test['Downtime (GROUPS)']

# Standardize train and test data

standard_X_train_fit=standard.fit(X_train)
X_trainT=standard_X_train_fit.transform(X_train)

standard_X_test_fit=standard.fit(X_test)
X_testT=standard_X_test_fit.transform(X_test)

models=[]
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))

results=[]
names=[]
for name, model in models:
  kfold = KFold(n_splits=12, random_state=7,shuffle=True)
  cv_results = cross_val_score(model, X_T, Y, cv=kfold, scoring='accuracy')
  results.append(cv_results)
  names.append(name)
  print('{} : {} (std={})'.format(name,round(cv_results.mean(),3),round(cv_results.std(),2)))


LR : 0.243 (std=0.21)
LDA : 0.354 (std=0.33)
KNN : 0.326 (std=0.28)
CART : 0.347 (std=0.21)
NB : 0.292 (std=0.21)
SVM : 0.243 (std=0.21)


## Selecting Linear Discrimintion model as the best model due to highest crosss validation score

In [16]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

model=LinearDiscriminantAnalysis()
model.fit(X_trainT,Y_train)
Y_predict=model.predict(X_testT)

target_names =['Low', 'Med', 'High', 'Very High']
print(classification_report(Y_test, Y_predict, target_names=target_names))
print (confusion_matrix(Y_predict,Y_test))

              precision    recall  f1-score   support

         Low       1.00      0.33      0.50         3
         Med       0.00      0.00      0.00         2
        High       0.00      0.00      0.00         1
   Very High       0.00      0.00      0.00         2

    accuracy                           0.12         8
   macro avg       0.25      0.08      0.12         8
weighted avg       0.38      0.12      0.19         8

[[1 0 0 0]
 [2 0 0 1]
 [0 2 0 1]
 [0 0 1 0]]
